import faker from '../../faker'
import DevicePosition from '../../types/devicePosition'
import createRandomDevicePosition from './createRandomDevicePosition'

const METRES_PER_DEGREE_LATITUDE = 111_320

/**
 * Projects a geographic position by a given distance and heading.
 *
 * Uses a simple equirectangular approximation to calculate a new latitude
 * and longitude from an origin point, distance, and bearing.
 *
 * @param latitude Origin latitude in decimal degrees.
 * @param longitude Origin longitude in decimal degrees.
 * @param distance Distance to travel in metres.
 * @param heading Bearing in degrees, where:
 * - 0 = North
 * - 90 = East
 * - 180 = South
 * - 270 = West
 * @returns The projected position as an object containing:
 * - `latitude`: The calculated latitude in decimal degrees.
 * - `longitude`: The calculated longitude in decimal degrees.
 */
const projectPosition = (latitude: number, longitude: number, distance: number, heading: number) => {
  const headingRad = (heading * Math.PI) / 180

  // North/south delta
  const northMetres = Math.cos(headingRad) * distance

  // East/west delta
  const eastMetres = Math.sin(headingRad) * distance

  // Convert metres to degrees
  const latChange = northMetres / METRES_PER_DEGREE_LATITUDE
  const lngChange = eastMetres / (METRES_PER_DEGREE_LATITUDE * Math.cos((latitude * Math.PI) / 180))

  return {
    latitude: latitude + latChange,
    longitude: longitude + lngChange,
  }
}

/**
 * Creates the next trail position from the current position.
 *
 * The position is first projected using the provided distance and heading, then
 * a small amount of GPS noise is added to make the generated trail look less
 * perfectly deterministic.
 *
 * @param latitude Current latitude in decimal degrees.
 * @param longitude Current longitude in decimal degrees.
 * @param distance Distance to move in metres.
 * @param heading Bearing in degrees.
 * @returns The next simulated GPS position.
 */
const createNextPosition = (latitude: number, longitude: number, distance: number, heading: number) => {
  // Calculate next position
  const nextPosition = projectPosition(latitude, longitude, distance, heading)

  // Add a small amount of GPS noise
  const noisyPosition = faker.location.nearbyGPSCoordinate({
    origin: [nextPosition.latitude, nextPosition.longitude],
    radius: 0.01, // ~10 metres
    isMetric: true,
  })

  return {
    latitude: noisyPosition[0],
    longitude: noisyPosition[1],
  }
}

/**
 * Generates an occasional random change in heading.
 *
 * Most points continue in the same direction. A heading change is only applied
 * 10% of the time to avoid unrealistic sharp turns at every generated point.
 *
 * @returns A heading adjustment in degrees.
 */
const createRandomChangeInHeading = () => {
  return (
    faker.helpers.maybe(
      () =>
        faker.number.float({
          min: -90,
          max: 90,
        }),
      { probability: 0.1 },
    ) || 0
  )
}

/**
 * Generates a random walking distance for the given time interval.
 *
 * Uses a walking speed between 0.8m/s and 1.8m/s, multiplied by the interval
 * duration.
 *
 * @param intervalSeconds Number of seconds between generated positions.
 * @returns Distance travelled in metres.
 */
const createRandomWalkingDistance = (intervalSeconds: number) => {
  const minSpeed = 0.8
  const maxSpeed = 1.8

  return faker.number.int({ min: minSpeed * intervalSeconds, max: maxSpeed * intervalSeconds })
}

/**
 * Creates a synthetic GPS trail representing plausible walking movement.
 *
 * The trail starts from either the provided coordinates or a random location
 * within the UK latitude/longitude bounds. Each subsequent point is
 * generated by moving forward by a random walking distance, occasionally
 * changing heading, and adding GPS noise.
 *
 * @param startLat Starting latitude in decimal degrees.
 * @param startLng Starting longitude in decimal degrees.
 * @param count Number of positions to generate.
 * @param intervalSeconds Number of seconds between generated positions.
 * @returns An array of generated device positions ordered by timestamp.
 */
const createRandomTrail = (
  startLat: number = faker.location.latitude({ min: 49.87, max: 55.81 }),
  startLng: number = faker.location.longitude({ min: -6, max: 1.9 }),
  count = faker.number.int({ min: 50, max: 100 }),
  intervalSeconds = 60,
): Array<DevicePosition> => {
  let lat = startLat
  let lng = startLng

  // Initial direction of travel
  let heading = faker.number.float({ min: 0, max: 360 })

  let timestamp = new Date()

  const points: DevicePosition[] = []

  for (let i = 0; i < count; i += 1) {
    // Don't make sudden turns every step
    heading += createRandomChangeInHeading()

    // Keep heading between 0 and 360
    heading = (heading + 360) % 360

    // Random movement distance in metres
    const distance = createRandomWalkingDistance(intervalSeconds)

    // Calculate next position
    const nextPosition = createNextPosition(lat, lng, distance, heading)

    lat = nextPosition.latitude
    lng = nextPosition.longitude

    points.push({
      ...createRandomDevicePosition(),
      latitude: lat,
      longitude: lng,
      timestamp,
    })

    timestamp = new Date(timestamp.getTime() + intervalSeconds * 1000)
  }

  return points
}

export default createRandomTrail
