type PoliceForceArea =
  | 'Avon and Somerset'
  | 'Bedfordshire'
  | 'Cheshire'
  | 'CoLP'
  | 'Cumbria'
  | 'Derbyshire'
  | 'Durham'
  | 'Essex'
  | 'Gloucestershire'
  | 'Gwent'
  | 'Hampshire'
  | 'Hertfordshire'
  | 'Humberside'
  | 'Kent'
  | 'Metropolitan'
  | 'NorthWales'
  | 'Nottinghamshire'
  | 'Sussex'
  | 'WestMidlands'

export default PoliceForceArea
